[package]
name = "transformer"
version = "0.1.0"
edition = "2024"

[dependencies]
wit-bindgen = "0.44.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:transformer"

[package.metadata.component.dependencies]
